### ISSUE TITLE
Accepting a .csv file from the parser to populate initial queue

### ISSUE THREAD

**Issue by kstapelfeldt** [UTMediaCAT/mediacat-domain-crawler#10]
Accept .csv from the parser to populate initial queue of domain crawler.

**Comment by kstapelfeldt** [comment]
@jacqueline-chan to post a link to the branch where preliminary work has been done.

**Comment by jacqueline-chan** [comment]
https://github.com/UTMediaCAT/mediacat-backend/blob/%238-constructing-backend-framework/commandline/app.js

**Comment by kstapelfeldt** [comment]
code has been written. Danhua will send to Raiyan, and then Raiyan will provide feedback or integrate.

**Comment by kstapelfeldt** [comment]
Raiyan currently working on this.

**Comment by kstapelfeldt** [comment]
Raiyan has integrated and needs to push after testing. Danhua gave Raiyan a .csv file for testing. So far it seems to be working, so Raiyan will make pull request soon.

**Comment by kstapelfeldt** [comment]
Raiyan came across a few bugs that he is squashing.

**Comment by RaiyanRahman** [comment]
The CSV reader works now and has been tested. All changes have been committed.
