### ISSUE TITLE
Issue:  Some domains only return one / a few links back.

### ISSUE THREAD

**Issue by jacqueline-chan** [UTMediaCAT/mediacat-domain-crawler#18]
Needs investigation and a solution

To see the list of domains that have this issue visit http://199.241.167.146:80 or look at the database on the server

**Comment by jacqueline-chan** [comment]
some suspicions: paywall

**Comment by kstapelfeldt** [comment]
Sometimes we are only getting one link back. 
http://972mag.com/ gets only one link - but doesn't have a paywall.
Need to investigate issue.

**Comment by jacqueline-chan** [comment]
@RaiyanRahman  to investigate

**Comment by kstapelfeldt** [comment]
Most likely because the crawl is so big with so many links in the queue. No testing as of yet on this issue to verify.

**Comment by kstapelfeldt** [comment]
Writing tests as part of the crawl review ticket (#19 ) - closing as the discussion is happening there.
