### ISSUE TITLE
Modification of crawler to gather plain text version of the crawled articles

### ISSUE THREAD

**Issue by kstapelfeldt** [UTMediaCAT/mediacat-domain-crawler#2]
Either by keeping currently discarded HTML, or by using something like: https://github.com/mozilla/readability

**Comment by RaiyanRahman** [comment]
The HTML content is now kept and with the help of readability, we can obtain the following data:
- Title
- Author Metadata
- HTML content of the article body only (including all links that are referenced in the article itself)
- Clean Text content of the article
- Length of the article in characters

Unfortunately this doesn't give us any information about the date of publication.

Question: Should we change how we obtain links from the HTML of the whole webpage or are we more interested in just links found inside the article body? The links found in the article body are more guaranteed to take the crawler to other articles. Getting links from the whole webpage often gives us many garbage links that are unusable.

**Comment by kstapelfeldt** [comment]
Great! I think we should just keep links inside articles as you suggest and iterate if that's not enough. Could discuss more on Tuesday.

**Comment by kstapelfeldt** [comment]
Output should contain: 

- Title
- Author Metadata
- Date (when we have metascraper integrated)
- HTML content of the article body only (including all links that are referenced in the article itself)
- A further property that contains a list of all URLs in the article
- Clean Text content of the article
- Length of the article in characters

**Comment by kstapelfeldt** [comment]
If there are additional fields that can be grabbed easily, we may as well add them.

**Comment by kstapelfeldt** [comment]
The JSON format looks great. We reviewed in the meeting.

**Comment by kstapelfeldt** [comment]
Add domain name crawled to JSON output.

**Comment by RaiyanRahman** [comment]
The found URLs (embedded links) are now able to figure out which URL they were found on.

**Comment by kstapelfeldt** [comment]
Every found URL can track its own URL. 
We need each URL to also store the domain name.

In JSON, both:
https://nyt.com/somearticle
domain = nyt.com

**Comment by kstapelfeldt** [comment]
Will be pushed in the next update. Work done.

**Comment by RaiyanRahman** [comment]
All work has been pushed and a PR has been created.
