### ISSUE TITLE
Integrate Date Detection into crawler

### ISSUE THREAD

**Issue by kstapelfeldt** [UTMediaCAT/mediacat-domain-crawler#6]
Integration of https://www.npmjs.com/package/metascraper

**Comment by kstapelfeldt** [comment]
Write a function/service that, based on a URL list, will asynchronously retrieve all of the dates.

**Comment by kstapelfeldt** [comment]
Take all the links from the domain crawler output JSON and make the calls to retrieve dates and other append metadata and update to append this data to the existing JSON.

**Comment by kstapelfeldt** [comment]
Integration of metascraper is not complete - metascraper runs aync. Alex has tried two separate different approaches but still a lot of bugs. 

Some of the functions are being tested. There are two versions that he is working on but each have separate issues. metascraper being async complicates things. 

Appears that things are timing out.

**Comment by kstapelfeldt** [comment]
Alex worked on this but still roadblocks. If metascraper doesn't connect it hangs. Alex still working on issues (and making some progress) a lot of work has been done. 

Alex talked to @jacqueline-chan - she will review his work and see if she can work around it.

**Comment by jacqueline-chan** [comment]
Reviewed Alex's work - He was definitely headed in the right direction!
I redid his script as getDates.js under the same branch and it should work now.
I will leave @AlAndr04 to review, test and continue from it if need be.

**Comment by kstapelfeldt** [comment]
Alex is continuing this work. He has tested @jacqueline-chan 's work and confirms that it works! (yay!).  Right now it seems to populate into a list but need to confirm it will concatenate to the rest of the domain scraper output JSON and we need to add additional parameters for information besides the date.

**Comment by jacqueline-chan** [comment]
JSON is now concatenated and looks like the example in this readme file: https://github.com/UTMediaCAT/mediacat-domain-crawler/blob/Metascraper/newCrawler/README.md

These changes are under the Metascraper branch
