### ISSUE TITLE
Modify filter to permit the storage of twitter URLs

### ISSUE THREAD

**Issue by kstapelfeldt** [UTMediaCAT/mediacat-domain-crawler#9]
As per ticket subject.

**Comment by kstapelfeldt** [comment]
This is a blocker as we need to store twitter URLs so we can successfully interlink the tweets and news articles. @jacqueline-chan this needs to be checked before we start the crawl.

**Comment by AlAndr04** [comment]
The twitter urls are being included in the JSON now. It is in the filter branch

**Comment by RaiyanRahman** [comment]
I have reviewed the PR and it is good to go.
